# -*- coding: utf-8 -*-
"""cysecbootproject.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1tg9CyP0UXdlnrVBhyhAR7yb9sscqd8rA
"""

import requests
from datetime import datetime

api_key='54c9d2c41f7206271875d97fd5793e5f'
location = input("Enter the city name: ")

complete_api_link = "http://api.openweathermap.org/data/2.5/weather?q="+location+"&appid="+api_key
api_link = requests.get(complete_api_link)
api_data = api_link.json()

temp_city = ((api_data['main']['temp'])-273.15)
weather_desc = api_data['weather'][0]['description']
hmdt = api_data['main']['humidity']
wind_spd = api_data['wind']['speed']
date_time = datetime.now().strftime("%d %b %Y | %I:%M:%S %p")

print('-----------------------------------------------------------')
print("Weather Stats for - {}  ||  {}".format(location.upper(), date_time))
print('-----------------------------------------------------------')

f = open("weather.txt","w") 
f.write("api_data")
f = open("weather.txt")
content = f.read() 
f.close()
print(content)